name: misinformation_detector
description: "AI-Powered Misinformation Detection & Education App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^16.2.1
  
  # Network & API
  dio: ^5.4.0
  connectivity_plus: ^7.0.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Image & Media
  image_picker: ^1.0.5
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.2
  share_plus: ^12.0.0
  
  # Authentication
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  
  # Analytics & Crash Reporting
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.1
  
  # Notifications
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  
  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # Animations
  lottie: ^3.0.0
  animations: ^2.0.11
  
  # Forms & Validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  
  # Charts & Visualization
  fl_chart: ^1.1.0
  percent_indicator: ^4.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
