// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT5h1SqMl_U0E0S4pcd1Cawk0sAAuNMms',
    appId: '1:225702147709:web:81c8aa5fcb47c06f8e6314',
    messagingSenderId: '225702147709',
    projectId: 'chicha-380b1',
    authDomain: 'chicha-380b1.firebaseapp.com',
    storageBucket: 'chicha-380b1.firebasestorage.app',
    measurementId: 'G-RG77V0FY8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT5h1SqMl_U0E0S4pcd1Cawk0sAAuNMms',
    appId: '1:225702147709:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '225702147709',
    projectId: 'chicha-380b1',
    storageBucket: 'chicha-380b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5h1SqMl_U0E0S4pcd1Cawk0sAAuNMms',
    appId: '1:225702147709:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '225702147709',
    projectId: 'chicha-380b1',
    storageBucket: 'chicha-380b1.firebasestorage.app',
    iosBundleId: 'com.truthlens.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT5h1SqMl_U0E0S4pcd1Cawk0sAAuNMms',
    appId: '1:225702147709:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '225702147709',
    projectId: 'chicha-380b1',
    storageBucket: 'chicha-380b1.firebasestorage.app',
    iosBundleId: 'com.truthlens.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT5h1SqMl_U0E0S4pcd1Cawk0sAAuNMms',
    appId: '1:225702147709:web:81c8aa5fcb47c06f8e6314',
    messagingSenderId: '225702147709',
    projectId: 'chicha-380b1',
    storageBucket: 'chicha-380b1.firebasestorage.app',
  );
}